### ISSUE TITLE
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.Parameter name: start (in v3.0.290)

### ISSUE THREAD

**Issue by Jemsband** [mburbea/koar-item-editor#118] opened 2021-12-18 03:18 UTC
**Describe the bug**

**To Reproduce**

**System Information**
 - OS: [e.g. Windows 10 2004]
 - Game version [e.g. Stream, GOG and please include the CS]
 - Version of the editor: [e.g. 3.0.347]

**Additional context**
Please also attach a save file that exhibits the issue.

**Comment by mburbea** [comment] 2021-12-18 04:11
Dupe of #114

**Closed by mburbea** 2021-12-18 04:11 UTC
Labels: bug
