### ISSUE TITLE
System.IndexOutOfRangeException: Index was outside the bounds of the array. (in v3.0.331)

### ISSUE THREAD

**Issue by cinderofsouls** [mburbea/koar-item-editor#115] opened 2021-12-16 13:04 UTC
**Describe the bug**
Error when loading save.

**To Reproduce**
1. Load save, nothing else.

**System Information**
 - OS: Tested on both EndeavourOS linux and on a windows 10 21H2 vm.
 - Game version: Steam cs:13779. It's a cracked version to test if the game works on linux, and it does, so I'll be buying it on steam soon and I can test there too if it would make a difference
 - Version of the editor: v3.0.331

**Additional context**
[svd_fmt_5_11.sav.tar.gz](https://github.com/mburbea/koar-item-editor/files/7727425/svd_fmt_5_11.sav.tar.gz)
It's possible I have missing dependencies as it isn't very clear what needs to be installed. Wine comes with practically nothing and it is a fresh windows vm. On wine, I installed dotnet48. On windows, I installed the .net 6.0 desktop runtime, which also appears to include the same thing I installed on wine.

**Comment by Auriejir** [comment] 2021-12-16 17:56
I have the same issue with a new save on windows 10. 
did they change the save format in the last patch or the previous one ?

**Comment by mburbea** [comment] 2021-12-17 21:01
Dupe of #114

**Closed by mburbea** 2021-12-17 21:01 UTC
Labels: bug
